name: Scrape YLB Articles

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch: # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install selenium

      - name: Run scraper script
        run: python scrape_ylb.py

      - name: Commit & Push Updated JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add articles.json
          git commit -m "Update articles.json" || echo "No changes to commit"
          git push
